"use client";
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {supabase} from "@/lib/supabase";

type Itinerary={day:number,title:string,description:string};
export default function EditPackage(){
 const {id}=useParams<{id:string}>(); const r=useRouter(); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 const [form,setForm]=useState<any>({title:"",slug:"",short_description:"",description:"",price:"",duration_days:"",difficulty:"",max_altitude_m:"",group_size:"",best_season:"",hero_image_url:"",featured:false,is_active:true,includes:"",excludes:""});
 const [itinerary,setItinerary]=useState<Itinerary[]>([]);
 useEffect(()=>{(async()=>{const {data,error}=await supabase.from("xyz_packages").select("*").eq("id",id).single();if(error){alert(error.message);return r.push("/admin/packages")}setForm({...data,price:data.price??"",duration_days:data.duration_days??"",max_altitude_m:data.max_altitude_m??"",includes:(data.includes||[]).join("\n"),excludes:(data.excludes||[]).join("\n")});setItinerary(Array.isArray(data.itinerary)?data.itinerary:[]);setLoading(false)})()},[id,r]);
 function set(k:string,v:any){setForm((x:any)=>({...x,[k]:v}))}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);const payload={...form,price:form.price?Number(form.price):null,duration_days:form.duration_days?Number(form.duration_days):null,max_altitude_m:form.max_altitude_m?Number(form.max_altitude_m):null,includes:form.includes.split("\n").map((x:string)=>x.trim()).filter(Boolean),excludes:form.excludes.split("\n").map((x:string)=>x.trim()).filter(Boolean),itinerary};delete payload.id;delete payload.created_at;delete payload.updated_at;delete payload.category_id;delete payload.destination_id;delete payload.gallery_urls;const {error}=await supabase.from("xyz_packages").update(payload).eq("id",id);setSaving(false);if(error)alert(error.message);else alert("Package saved successfully")}
 if(loading)return <main className="admin"><div className="admin-wrap">Loading…</div></main>;
 return <main className="admin"><div className="admin-nav"><strong>XYZ Treks & Tours — Edit Package</strong><button className="btn light" onClick={()=>r.push("/admin/packages")}>Back</button></div><div className="admin-wrap"><form className="form" onSubmit={save}><h1>Edit Package</h1>
 <div className="row"><div className="field"><label>Title *</label><input required value={form.title} onChange={e=>set("title",e.target.value)}/></div><div className="field"><label>Slug</label><input value={form.slug} onChange={e=>set("slug",e.target.value)}/></div></div>
 <div className="field"><label>Short description</label><textarea value={form.short_description||""} onChange={e=>set("short_description",e.target.value)}/></div><div className="field"><label>Full description</label><textarea value={form.description||""} onChange={e=>set("description",e.target.value)}/></div>
 <div className="row"><div className="field"><label>Price (USD)</label><input type="number" value={form.price} onChange={e=>set("price",e.target.value)}/></div><div className="field"><label>Duration (days)</label><input type="number" value={form.duration_days} onChange={e=>set("duration_days",e.target.value)}/></div></div>
 <div className="row"><div className="field"><label>Difficulty</label><input value={form.difficulty||""} onChange={e=>set("difficulty",e.target.value)}/></div><div className="field"><label>Max altitude (m)</label><input type="number" value={form.max_altitude_m} onChange={e=>set("max_altitude_m",e.target.value)}/></div></div>
 <div className="row"><div className="field"><label>Group size</label><input value={form.group_size||""} onChange={e=>set("group_size",e.target.value)}/></div><div className="field"><label>Best season</label><input value={form.best_season||""} onChange={e=>set("best_season",e.target.value)}/></div></div>
 <div className="field"><label>Hero image</label><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`packages/${id}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from("xyz-media").upload(path,file,{contentType:file.type,upsert:true});if(error){alert(error.message);return}const {data}=supabase.storage.from("xyz-media").getPublicUrl(path);set("hero_image_url",data.publicUrl)}}/><input value={form.hero_image_url||""} placeholder="Or paste image URL" onChange={e=>set("hero_image_url",e.target.value)}/></div>
 <div className="row"><div className="field"><label>Includes (one per line)</label><textarea value={form.includes} onChange={e=>set("includes",e.target.value)}/></div><div className="field"><label>Excludes (one per line)</label><textarea value={form.excludes} onChange={e=>set("excludes",e.target.value)}/></div></div>
 <h2>Itinerary</h2>{itinerary.map((x,i)=><div className="card" style={{padding:15,marginBottom:12}} key={i}><div className="row"><div className="field"><label>Day</label><input type="number" value={x.day} onChange={e=>{const a=[...itinerary];a[i]={...a[i],day:Number(e.target.value)};setItinerary(a)}}/></div><div className="field"><label>Title</label><input value={x.title} onChange={e=>{const a=[...itinerary];a[i]={...a[i],title:e.target.value};setItinerary(a)}}/></div></div><div className="field"><label>Description</label><textarea value={x.description} onChange={e=>{const a=[...itinerary];a[i]={...a[i],description:e.target.value};setItinerary(a)}}/></div><button type="button" className="btn" onClick={()=>setItinerary(itinerary.filter((_,j)=>j!==i))}>Remove Day</button></div>)}
 <button type="button" className="btn light" onClick={()=>setItinerary([...itinerary,{day:itinerary.length+1,title:"",description:""}])}>+ Add Day</button>
 <div style={{marginTop:25,display:"flex",gap:12}}><label><input type="checkbox" checked={!!form.featured} onChange={e=>set("featured",e.target.checked)}/> Featured</label><label><input type="checkbox" checked={!!form.is_active} onChange={e=>set("is_active",e.target.checked)}/> Published</label></div>
 <br/><button className="btn primary" disabled={saving}>{saving?"Saving…":"Save Package"}</button></form></div></main>
}